# -*- coding: utf-8 -*-
"""limpieza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNlJUiah0mMOXFjQZ1cKVUHC45GaFEpe
"""



#Clase de Limpieza y Renombrado (LimpiezaBasica)

#Importar librerias
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
# Crear Class para limpieza basica

class LimpiezaBasica(BaseEstimator, TransformerMixin):
    """
    Clase para estandarizar nombres de columnas, imputar nulos y
    preparar el dataset para el modelo de riesgos.
    """

# Def init creo parámetros de configuración.
# No mira los datos todavía, solo sabe qué columnas va a tener que vigilar.
    def __init__(self):
        # NOTA: Diccionario para pasar de nombres técnicos/largos a nombres claros (EDA)
        self.rename_dict = {
            'SeriousDlqin2yrs': 'Impago2Años',
            'RevolvingUtilizationOfUnsecuredLines': 'UsoCrédito',
            'age': 'Edad',
            'NumberOfTime30-59DaysPastDueNotWorse': '30-59DíasTarde',
            'NumberOfTime60-89DaysPastDueNotWorse': '60-89DíasTarde',
            'NumberOfTimes90DaysLate': '90DíasTarde',
            'DebtRatio': 'RatioDeuda',
            'MonthlyIncome': 'IngresoMensual',
            'NumberOfOpenCreditLinesAndLoans': 'LíneasCrédito',
            'NumberRealEstateLoansOrLines': 'PréstamosCasa',
            'NumberOfDependents': 'Dependientes'
        }

        # Guardas la lista columns_to_keep. Es como decirle:
        # "Ten esta lista, solo te quedarás con estas columnas cuando termines".
        # NOTA: Definimos el orden final de las columnas que queremos conservar
        self.columns_to_keep = list(self.rename_dict.values())

# El Entrenamiento: def fit(self, X, y=None)
# fase de aprendizaje o memoria: Se calculan estadísticas (medias, medianas, modas).
# ¡IMPORTANTE! Aquí no se cambia nada, solo se calcula y se guarda.
    def fit(self, X, y=None):
        """
        NOTA: Aquí el objeto 'aprende' de los datos de entrenamiento.
        Calculamos la MEDIANA del ingreso para usarla como relleno en el futuro.
        """
        # Renombramos temporalmente para encontrar la columna 'IngresoMensual' de forma segura
        X_temp = X.rename(columns=self.rename_dict)

        # Guardamos la mediana y la moda en la memoria del objeto (self.)
        # Añadimos comprobación 'if' por seguridad técnica si faltan columnas
        if 'IngresoMensual' in X_temp.columns:
            self.ingreso_median_ = X_temp['IngresoMensual'].median()
        else:
            self.ingreso_median_ = 0

        if 'Dependientes' in X_temp.columns:
            self.dep_mode_ = X_temp['Dependientes'].mode()[0]
        else:
            self.dep_mode_ = 0

        # return self: Es necesario para que Scikit-Learn sepa que el objeto
        # ya terminó de aprender y está listo para ser usado.
        return self

    # def transform(self, X) ¿Qué es?: Es la fase de acción.
    def transform(self, X):
        """
        NOTA: Aquí aplicamos los cambios a cualquier dataset (Train, Test o nuevos).
        """
        # Trabajamos sobre una copia para no alterar el DataFrame original
        df_clean = X.copy()

        # 1. Renombrado de todas las columnas según el diccionario
        df_clean = df_clean.rename(columns=self.rename_dict)

        # 2. Imputación de Nulos (Usando lo aprendido en el FIT)
        # Rellenamos los huecos del Ingreso y los Dependientes
        df_clean['IngresoMensual'] = df_clean['IngresoMensual'].fillna(self.ingreso_median_)
        df_clean['Dependientes'] = df_clean['Dependientes'].fillna(self.dep_mode_)

        # 3. Ajuste de consistencia (Edad mínima 18)
        # NOTA: En lugar de borrar la fila, subimos la edad a 18 para no romper el vector X.
        # (Los menores de 18 ya los borramos físicamente en el paso de carga previo).
        df_clean.loc[df_clean['Edad'] < 18, 'Edad'] = 18

        # 4. Limpieza de errores en retrasos (Valores 96 y 98 detectados en EDA)
        # NOTA: En banca, si hay un código de error en retrasos, lo normalizamos a 0
        # para que el modelo no cree que son "98 meses de retraso".
        cols_retraso = ['30-59DíasTarde', '60-89DíasTarde', '90DíasTarde']
        for col in cols_retraso:
            if col in df_clean.columns:
                df_clean.loc[df_clean[col] >= 90, col] = 0

        # 5. Devolvemos el DataFrame con los nombres nuevos y el orden correcto
        # Buscamos solo las columnas que están en nuestra lista 'columns_to_keep'
        existing_cols = [c for c in self.columns_to_keep if c in df_clean.columns]
        return df_clean[existing_cols]

# print("Clase LimpiezaBasica lista para ejecutar.")